/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IAsset, IAssetInterface } from "../IAsset";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balanceOf",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "burn",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "transferUnderlyingToken",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IAsset__factory {
  static readonly abi = _abi;
  static createInterface(): IAssetInterface {
    return new utils.Interface(_abi) as IAssetInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): IAsset {
    return new Contract(address, _abi, signerOrProvider) as IAsset;
  }
}
