/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IRewarder, IRewarderInterface } from "../IRewarder";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "newLpAmount",
        type: "uint256",
      },
    ],
    name: "onJoeReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "pendingTokens",
    outputs: [
      {
        internalType: "uint256",
        name: "pending",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "rewardToken",
    outputs: [
      {
        internalType: "contract IERC20",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class IRewarder__factory {
  static readonly abi = _abi;
  static createInterface(): IRewarderInterface {
    return new utils.Interface(_abi) as IRewarderInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRewarder {
    return new Contract(address, _abi, signerOrProvider) as IRewarder;
  }
}
